name: Check Python on Windows ARM

on:
  workflow_dispatch:

jobs:
  check-python:
    runs-on: windows-11-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Python path with cmd
        shell: cmd
        run: where python

      - name: List all Python installations via py launcher
        run: py --list-paths

      - name: Show Python path with sys.executable
        run: python -c "import sys; print('Python executable:', sys.executable)"

      - name: Show Python version
        run: python --version

      - name: Show Python architecture
        run: python -c "import platform, struct; print('Platform:', platform.platform()); print('Machine:', platform.machine()); print('Arch:', struct.calcsize('P') * 8, 'bit')"

      - name: List all installed Pythons in hostedtoolcache
        run: Get-ChildItem "C:\hostedtoolcache\windows\Python\" -Recurse -Depth 2 | Select-Object FullName

      - name: List all installed Pythons in 3.11
        run: Get-ChildItem "C:\hostedtoolcache\windows\Python\3.11.9\" -Recurse -Depth 2 | Select-Object FullName
