name: Build Jiter Wheel on Windows ARM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          architecture: 'arm64'

      - name: Build Jiter wheel
        uses: PyO3/maturin-action@v1
        with:
          command: build
          rust-toolchain: stable
          target: aarch64
          args: --release --out dist --interpreter 3.11 3.12 3.13 3.13t 3.14 3.14t
          working-directory: crates/jiter-python
          sccache: false

      - name: Upload wheel artifact
        uses: actions/upload-artifact@v3
        with:
          name: jiter-wheel
          path: crates/jiter-python/dist/*.whl
