name: Check ARM KVM

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-26.04-arm

    steps:
      - name: CPU architecture
        run: |
          echo "Architecture:"
          uname -m

          echo
          echo "CPU:"
          lscpu

      - name: Check KVM
        run: |
          echo "Checking /dev/kvm..."

          if [ -e /dev/kvm ]; then
            echo "KVM device exists:"
            ls -l /dev/kvm

            if [ -r /dev/kvm ] && [ -w /dev/kvm ]; then
              echo "KVM device is accessible"
            else
              echo "KVM exists but is not accessible"
              exit 1
            fi
          else
            echo "KVM is NOT available"
            exit 1
          fi

      - name: Check QEMU
        run: |
          qemu-system-aarch64 --version || true
